### ISSUE TITLE
Channels 2 + Daphne + Nginx (using Docker)

### ISSUE THREAD

**Issue by bluesurfer** [django/channels#919]
I am trying to configure Channels 2 using Nginx as reverse proxy for Daphne. This is my compose basic configuration:

**base.yml**
```
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh

  nginx:
    build: ./compose/nginx
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:latest

  channelworker:
    <<: *django
    command: /start-channelworker.sh
    depends_on:
      - postgres
      - redis

  channelserver:
    <<: *django
    command: /start-channelserver.sh
    depends_on:
      - postgres
      - redis
```

**start-channelserver.sh**
`daphne -u /tmp/daphne.sock config.asgi:application -v 2`

**start-channelworker.sh**
`python manage.py runworker channels`

**nginx.conf**
```
http {
    upstream app {
        server django:5000;
    }

    upstream ws_server {
        server unix:/tmp/daphne.sock;
    }

    server {
        listen 80;
        listen [::]:80;

        # listen on both hosts
        server_name 192.168.99.100;

        # redirect to the https host (declared below)
        return 301 https://$server_name$request_uri;
    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl;

        # The host name to respond to
        server_name 192.168.99.100;
   
       ... SSL configuration omitted ...

        location / {
            try_files $uri @proxy_to_app;
        }

        location /ws/ {
            try_files $uri @proxy_to_ws;
        }

        location @proxy_to_ws {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_redirect off;

            proxy_pass   http://ws_server;
        }

        # django app
        location @proxy_to_app {
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Url-Scheme $scheme;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;

            proxy_pass   http://app;
        }
    }
}
```
--
## Logs

**channelserver**
```
channelserver_1  | 2018-02-20 14:09:08,842 INFO     Configuring endpoint unix:/tmp/daphne.sock
channelserver_1  | 2018-02-20 14:09:08,843 INFO     HTTPFactory starting on '/tmp/daphne.sock'
channelserver_1  | 2018-02-20 14:09:08,844 INFO     Starting factory <daphne.http_protocol.HTTPFactory object at 0x7f56691a17f0>
```

**channelworker**
` 2018-02-20 14:06:12,382 - INFO - runworker - Running worker for channels ['channels']`

**nginx**
200 error responses (websocket failed connection)

What am I missing? I believe there's some communication problem between nginx and channelserver but I do not understand how to debug this.

**Comment by bluesurfer** [comment]
Ok, I think I made it work. I abandon unix sockets in favour of standard TCP.

**Comment by proofit404** [comment]
Hi,

If there is no errors in the Daphne side, I don't think we can help to configure your environment.

**Comment by xolan** [comment]
I'm facing some issues with websockets behind nginx.

This is my nginx server definition:
```
# Enable upgrading of connection (and websocket proxying) depending on the
# presence of the upgrade field in the client request header
map $http_upgrade $connection_upgrade {
	default   upgrade;
	''        close;
}

upstream django {
    server lh8-tools:8000;
    keepalive 16;
}

server {
    listen 80;
    access_log  /var/log/nginx/lh8-tools_access.log;
    error_log  /var/log/nginx/lh8-tools_error.log;
    server_name <SNIP>;

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    client_max_body_size 20M;

    location /static {
        alias /var/www/lh8-tools/static/;
    }

    location /media {
        alias /var/www/lh8-tools/static/;
    }

    location / {
        proxy_pass          http://django;
        proxy_http_version  1.1;
        proxy_set_header    Host $server_name:$server_port;
        proxy_set_header    Upgrade $http_upgrade;
        proxy_set_header    Connection $connection_upgrade;
        proxy_set_header    X-Real-IP $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Host $server_name:$server_port;
    }

}
```

If I access port 8000 directly, it works as expected. On port 80 (proxied by nginx), I'm getting `WebSocket connection to 'ws://<host>/<path>' failed: Invalid frame header`

The Django application is running via supervisord, where the relevant command is:

```
pipenv run daphne -b 0.0.0.0 -p 8000 app.asgi:application
```

Any suggestions?

**Comment by andrewgodwin** [comment]
I'm afriad that, if there are no problems talking to Daphne directly, then it's an nginx configuration issue or similar, and I've not run into them recently enough to help debug. Sorry.

**Comment by bastbnl** [comment]
@xolan I"m running channels via nginx with Daphne and it appears to be working. I did see that message in older versions of channels. Are you running the latest version of the entire channels stack?

**Comment by xolan** [comment]
@bastbnl 
I'm currently on these versions:

```
django==2.0.2
channels==2.02
channels_redis==2.1.0
daphne==2.0.4
```

Still fiddling around with it. I'll post again if/when I figure out what the issue is.

**Comment by xolan** [comment]
I'm having the same issues when talking to Daphne on port 80.

The app is i Docker container though, defined as such:

```
version: '2.1'

services:
  lh8-tools-redis:
    image: redis:3.2.8
    ports:
      - 6379

  lh8-tools-db:
    image: postgres:9.6.2
    volumes:
      - lh8-tools_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "---"
      POSTGRES_USER: "---"
      POSTGRES_PASSWORD: "---"

  lh8-tools:
    container_name: lh8-tools
    build:
      context: ./dist/lh8-tools
      dockerfile: ./Dockerfile
    volumes:
      - ./dist/lh8-tools:/opt/lh8-tools
      - ./logs:/var/log/supervisord
    restart: always
    tty: true
    depends_on:
      - lh8-tools-redis
      - lh8-tools-db
    links:
      - lh8-tools-redis
      - lh8-tools-db
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      DJANGO_SETTINGS_MODULE: app.settings
      SUPERUSER_USER: ---
      SUPERUSER_EMAIL: ---
      SUPERUSER_PASS: ---
      DATABASE_HOST: "lh8-tools-db"
      DATABASE_NAME: "---"
      DATABASE_USER: "---"
      DATABASE_PASSWORD: "---"
      REDIS_HOST: lh8-tools-redis
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1-alpine
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - lh8-tools
    links:
      - lh8-tools
    ports:
      - "80:80"

volumes:
  lh8-tools_pg_data: {}
```

Daphne is started via `pipenv run daphne -b 0.0.0.0 -p 8000 --proxy-headers app.asgi:application`
