### ISSUE TITLE
Running channels with both ASGI and WSGI on k8s?

### ISSUE THREAD

**Issue by MilanPecov** [django/channels#936]
I'm currenly trying to deploy a small project using Django, channels and redis as backend.

```
Django==1.10.8
channels==1.1.8
daphne==1.4.2
```

And on k8s I have this setup

django-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: app-web-server-service
spec:
  ports:
  - name: django
    port: 8000
    targetPort: 8000
  selector:
    app: web
  type: NodePort
```
django-worker-deploy.yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-web-server-deploy
  labels:
    app: web
spec:
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: django
          image: {{ config('IMAGES_PATH') }}app-web:{{ config('APP_WEB_DJANGO_VERSION') }}
          command: ["/bin/sh", "-ec"]
          args:
            gunicorn --bind 0.0.0.0:8000 wsgi
          ports:
            - containerPort: 8000
```
daphne-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: app-web-daphne-service
spec:
  ports:
  - name: daphne
    port: 8001
    targetPort: 8001
  selector:
    app: daphne
  type: NodePort
```
daphne-deploy.yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-web-daphne-deploy
  labels:
    app: daphne
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: daphne
    spec:
      containers:
        - name: daphne
          image: {{ config('IMAGES_PATH') }}app-web:{{ config('APP_WEB_DJANGO_VERSION') }}
          args:
            daphne asgi:channel_layer -b 0.0.0.0 -p 8001 -v 2;
          ports:
            - containerPort: 8001
```

Hosted through nginx like this

```
server {
    listen 80;
    {# redirect HTTP to HTTPS #}
    location / {
      return 301 https://{% if config('APP_WEB_SITE_URL') %}{{ config('APP_WEB_SITE_URL') }}{% else %}$host{% endif %}$request_uri;
    }
}


server {
  listen 443 http2;

  {% if config('APP_WEB_SITE_URL') %}
  server_name {{ config('APP_WEB_SITE_URL') }} app-main-entrypoint-service localhost;
  {% endif %}


  location /ws/ {
    proxy_pass http://app-web-daphne-service:8001/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

  location / {
    proxy_intercept_errors on;
    proxy_pass http://app-web-server-service:8000/;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Protocol $scheme;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

  }
}
```

The websockets app (which works good if I run everything through asgi) is not giving me any console errors. However after the initial "subscribe" message is sent through the channel (without errors)

```
DEBUG    WebSocket daphne.response.DyiUcnNLhG!dNtTxnexnt open and established
         "WSCONNECT /" - -
DEBUG    WebSocket daphne.response.DyiUcnNLhG!dNtTxnexnt accepted by application
DEBUG    WebSocket incoming frame on daphne.response.DyiUcnNLhG!dNtTxnexnt
DEBUG    Sent WebSocket packet to client for daphne.response.DyiUcnNLhG!dNtTxnexnt
```

new actions ("create", "delete"... ) are not sent and received anymore. Any ideas what am I doing wrong and how to further debug this?
